repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: Mypy static type checking
        args: ["--config-file", "./pyproject.toml"]
        additional_dependencies: [
          "fastapi[standard]>=0.115.0,<1.0.0",
          "pytest>=8.3.0,<9.0.0"
        ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        name: Ruff code linting
      - id: ruff-format
        name: Ruff code formatting

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        name: Bandit security linting
        args: ["--configfile", "./pyproject.toml"]
